### ISSUE TITLE
Missing net.java.html.boot.fx-1.1.js

### ISSUE THREAD

**Issue by konsoletyper** [dukescript/fifteen#3]
I could fix the [previous issue](https://github.com/dukescript/fifteen/issues/2), but I still can't run application. Google Chrome says that it can't find `lib/net.java.html.boot.fx-1.1.js`. I looked through `pom.xml` and found that `net.java.html.boot.fx` artifact is excluded. Removing exclusion causes lots of compile-time errors.

**Comment by dukescript** [comment]
Did you receive my previous mails? I fixed these issues in the merged branch.

—Toni

Am 30.06.2015 um 21:01 schrieb Alexey Andreev notifications@github.com:
